package view;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hasan
 */
public class Hakkimizda extends javax.swing.JFrame {

    /**
     * Creates new form Hakkimizda
     */
    public Hakkimizda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        geri_git_butonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HAKKIMIZDA");
        setBounds(new java.awt.Rectangle(700, 250, 0, 0));
        setSize(new java.awt.Dimension(500, 350));

        jScrollPane1.setForeground(new java.awt.Color(153, 153, 153));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea1.setRows(5);
        jTextArea1.setText("Hakkımızda : \nAyşe İpek Yılmaz, Hasan Ali Yıldır, Nevin İn, \nKenan Yılmaz, Özlem Yılmaz ile beraber \ngeliştirdiğimiz bu proje Yazılım Mühendisliği\ndersi ödevi olarak geliştirilmiştir.\nProgram eğer daha fazla geliştirilirse\ngelecek vaad eden bir yapıya kavuşabilir.\nProgramın amacı kişinin seçtiği sigorta \nalanına uygun olarak belirtilen özellikler ile \nkişinin tercih ettiği sigorta kapsamında\nen uygun fiyatlandırmayı yapmayı hedefler.\nÖrneğin : Kişi araç sigortası kısmını seçip \ngerekli bilgi alanlarını doldurduktan sonra\n(araç yaşı, araç cinsi, kaza geçmişi, ticari\nolup olmadığı vb.) seçilen kriterlere göre en \nuygun fiyatlandırmayı yapmayı hedefler,\nfiyatlandırma durumu yasal olarak çeşitli \naraştırmalar sonucu elde ettiğimiz bilgiler\nsonucunda en uygun değeri çıkarmaktır.\nHesaplamada kullanılan rakamlar tam olarak\ngerçeği yansıtmasada piyasa düzeyinde\nalt ve üst sınır çerçevesinde bir fiyat ortaya\nkoyar.\n\nVizyonumuz : \nKullanıcı/Kişilere en uygun şekilde ve hızlı \nbir biçimde veri akışı sağlamaktır.\n\nMisyonumuz : \nProgramımızı gün ve gğn geliştirerek daha\ngüncel veriler ışığında, kullanıcı dostu \nolmayı hedefler. Kişilerin serbest piyasa \nortamında madur olmaması için çabalar.\nBunun için BIGGANG SİGORTA A.Ş olarak\nen uygun seçenekleri bulmaya yardımcı \nolur.\nBizi Tercih Ettiğiniz İçin Teşekkür Ederiz.\nBIGGANG SİGORTA A.Ş Topluluğu\n\n");
        jTextArea1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jScrollPane1.setViewportView(jTextArea1);

        geri_git_butonu.setBackground(new java.awt.Color(204, 204, 204));
        geri_git_butonu.setForeground(new java.awt.Color(51, 51, 51));
        geri_git_butonu.setText("HESAPLAMA SAYFASINA DÖN");
        geri_git_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geri_git_butonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(geri_git_butonu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geri_git_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geri_git_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geri_git_butonuActionPerformed
       // JOptionPane.showMessageDialog(this, "Hesaplama sayfasına dönüyorsunuz...");
        setVisible(false);
    }//GEN-LAST:event_geri_git_butonuActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton geri_git_butonu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
