package view;


import java.awt.Desktop;
import java.awt.Image;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hasan
 */
public class HesapAlani extends javax.swing.JFrame {
private String kadi,adi,soyadi,email;
private int aracCarpani,yasCarpani,modelCarpani,kazaCarpani,depremKazaCarpani,hastalikCarpani,hyCarpani,kgCarpani,binaYas,katNo;
    public JLabel getAd_alani() {
        return ad_alani;
    }

    public void setAd_alani(JLabel ad_alani) {
        this.ad_alani = ad_alani;
    }

  
    public JLabel getEmail_alani() {
        return email_alani;
    }

    public void setEmail_alani(JLabel email_alani) {
        this.email_alani = email_alani;
    }

    public JLabel getKullanici_adi_alani() {
        return kullanici_adi_alani;
    }

    public void setKullanici_adi_alani(JLabel kullanici_adi_alani) {
        this.kullanici_adi_alani = kullanici_adi_alani;
    }

    public JLabel getSoyad_alani() {
        return soyad_alani;
    }

    public void setSoyad_alani(JLabel soyad_alani) {
        this.soyad_alani = soyad_alani;
    }
    
    

    /**
     * Creates new form HesapAlani
     */
    public HesapAlani(String kadi,String adi,String soyadi,String email) {
        initComponents();
        this.kadi=kadi;
        this.adi=adi;
        this.soyadi=soyadi;
        this.email=email;
        this.kullanici_adi_alani.setText(kadi);
        this.ad_alani.setText(adi);
        this.soyad_alani.setText(soyadi);
        this.email_alani.setText(email);
        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kullanici_adi_alani = new javax.swing.JLabel();
        ad_alani = new javax.swing.JLabel();
        soyad_alani = new javax.swing.JLabel();
        email_alani = new javax.swing.JLabel();
        cikis_butonu = new javax.swing.JButton();
        kalan = new javax.swing.JPanel();
        hesap_butonu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sonuc_ekrani = new javax.swing.JTextArea();
        tabbed_pane = new javax.swing.JTabbedPane();
        arac_paneli = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        yas_secim = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        model_secim = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        kaza_secim = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        ton_secim = new javax.swing.JComboBox();
        saglik_paneli = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        insan_yas = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        has_secim = new javax.swing.JComboBox();
        deprem_paneli = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        bina_yas_secim = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        bina_hasar = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        bina_kat = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        twitter_butonu = new javax.swing.JButton();
        facebook_butonu = new javax.swing.JButton();
        instagram_butonu = new javax.swing.JButton();
        hakkimizda_butonu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HESAPLAMA ALANI");
        setBounds(new java.awt.Rectangle(700, 250, 0, 0));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kullanıcı Adı : ");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ad : ");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Soyad :");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email Adresi : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(email_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(soyad_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addComponent(kullanici_adi_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ad_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(kullanici_adi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(email_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        cikis_butonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon-error.png"))); // NOI18N
        cikis_butonu.setText("Çıkış Yap");
        cikis_butonu.setMaximumSize(new java.awt.Dimension(50, 50));
        cikis_butonu.setMinimumSize(new java.awt.Dimension(50, 50));
        cikis_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikis_butonuActionPerformed(evt);
            }
        });

        kalan.setBackground(new java.awt.Color(204, 204, 255));
        kalan.setForeground(new java.awt.Color(204, 204, 255));

        hesap_butonu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        hesap_butonu.setForeground(new java.awt.Color(0, 0, 0));
        hesap_butonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconfinder_Finance_finance_calculator_1889192.png"))); // NOI18N
        hesap_butonu.setText("Hesapla");
        hesap_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesap_butonuActionPerformed(evt);
            }
        });

        sonuc_ekrani.setColumns(20);
        sonuc_ekrani.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        sonuc_ekrani.setForeground(new java.awt.Color(51, 51, 51));
        sonuc_ekrani.setRows(5);
        jScrollPane1.setViewportView(sonuc_ekrani);

        tabbed_pane.setForeground(new java.awt.Color(255, 255, 255));
        tabbed_pane.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("YAŞ :");

        yas_secim.setForeground(new java.awt.Color(255, 255, 255));
        yas_secim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEÇİNİZ : ", "1-5", "6-10", "10+", " " }));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("MODEL");

        model_secim.setForeground(new java.awt.Color(255, 255, 255));
        model_secim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEÇİNİZ : ", "SEDAN", "TİCARİ", "HATCBACK" }));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("KAZA");

        kaza_secim.setForeground(new java.awt.Color(255, 255, 255));
        kaza_secim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEÇİNİZ :", "VAR", "YOK" }));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("ARAÇ AĞIRLIĞI : ");

        ton_secim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEÇİNİZ(TON) :", "1-2", "3-5", "6+" }));

        javax.swing.GroupLayout arac_paneliLayout = new javax.swing.GroupLayout(arac_paneli);
        arac_paneli.setLayout(arac_paneliLayout);
        arac_paneliLayout.setHorizontalGroup(
            arac_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arac_paneliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(arac_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(arac_paneliLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(yas_secim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(model_secim, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(kaza_secim, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(arac_paneliLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ton_secim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        arac_paneliLayout.setVerticalGroup(
            arac_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arac_paneliLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(arac_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(yas_secim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(model_secim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(kaza_secim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(arac_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ton_secim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        tabbed_pane.addTab("ARAÇ", arac_paneli);

        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("YAŞ : ");

        insan_yas.setForeground(new java.awt.Color(255, 255, 255));
        insan_yas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEÇİNİZ :", "17-", "18-24", "25-64", "65+" }));

        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("HASTALIK :");

        has_secim.setForeground(new java.awt.Color(255, 255, 255));
        has_secim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEÇİNİZ :", "HASTALIK YOK", "KALP", "BEYİN", " " }));

        javax.swing.GroupLayout saglik_paneliLayout = new javax.swing.GroupLayout(saglik_paneli);
        saglik_paneli.setLayout(saglik_paneliLayout);
        saglik_paneliLayout.setHorizontalGroup(
            saglik_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saglik_paneliLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insan_yas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(has_secim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );
        saglik_paneliLayout.setVerticalGroup(
            saglik_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saglik_paneliLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(saglik_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(insan_yas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(has_secim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        tabbed_pane.addTab("SAĞLIK", saglik_paneli);

        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("BİNA YAŞI : ");

        bina_yas_secim.setForeground(new java.awt.Color(255, 255, 255));
        bina_yas_secim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEÇİNİZ :", "1-5", "6-9", "10+" }));

        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("HASAR VAR MI?");

        bina_hasar.setForeground(new java.awt.Color(255, 255, 255));
        bina_hasar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEÇİNİZ :", "YOK", "VAR" }));

        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("KAT NO :");

        bina_kat.setForeground(new java.awt.Color(255, 255, 255));
        bina_kat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEÇİNİZ :", "MÜSTAKİL", "BODRUM", "1-2", "3-5", "6-10", "10+" }));

        javax.swing.GroupLayout deprem_paneliLayout = new javax.swing.GroupLayout(deprem_paneli);
        deprem_paneli.setLayout(deprem_paneliLayout);
        deprem_paneliLayout.setHorizontalGroup(
            deprem_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deprem_paneliLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(deprem_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(deprem_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bina_kat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bina_yas_secim, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(jLabel14)
                .addGap(31, 31, 31)
                .addComponent(bina_hasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        deprem_paneliLayout.setVerticalGroup(
            deprem_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deprem_paneliLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(deprem_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(bina_yas_secim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(bina_hasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(deprem_paneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(bina_kat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        tabbed_pane.addTab("DEPREM", deprem_paneli);

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BIGGANG SİGORTA A.Ş");

        javax.swing.GroupLayout kalanLayout = new javax.swing.GroupLayout(kalan);
        kalan.setLayout(kalanLayout);
        kalanLayout.setHorizontalGroup(
            kalanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kalanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kalanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kalanLayout.createSequentialGroup()
                        .addComponent(hesap_butonu)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kalanLayout.createSequentialGroup()
                        .addGroup(kalanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kalanLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tabbed_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kalanLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53))))
        );
        kalanLayout.setVerticalGroup(
            kalanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kalanLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(tabbed_pane)
                .addGap(18, 18, 18)
                .addGroup(kalanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kalanLayout.createSequentialGroup()
                        .addComponent(hesap_butonu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(15, 15, 15))
        );

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconfinder_arrow-down-right_59810.png"))); // NOI18N
        jLabel7.setText("Sosyal Medya Adreslerimiz : ");

        twitter_butonu.setBackground(new java.awt.Color(51, 51, 255));
        twitter_butonu.setForeground(new java.awt.Color(255, 255, 255));
        twitter_butonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconfinder_twitter_312527.png"))); // NOI18N
        twitter_butonu.setText("Twitter");
        twitter_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twitter_butonuActionPerformed(evt);
            }
        });

        facebook_butonu.setBackground(new java.awt.Color(0, 51, 153));
        facebook_butonu.setForeground(new java.awt.Color(255, 255, 255));
        facebook_butonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconfinder_facebook_295880 (1).png"))); // NOI18N
        facebook_butonu.setText("Facebook");
        facebook_butonu.setMaximumSize(new java.awt.Dimension(189, 115));
        facebook_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facebook_butonuActionPerformed(evt);
            }
        });

        instagram_butonu.setBackground(new java.awt.Color(153, 0, 153));
        instagram_butonu.setForeground(new java.awt.Color(255, 255, 255));
        instagram_butonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconfinder_social-media_instagram_1543322.png"))); // NOI18N
        instagram_butonu.setText("Instagram");
        instagram_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instagram_butonuActionPerformed(evt);
            }
        });

        hakkimizda_butonu.setText("Hakkımızda");
        hakkimizda_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hakkimizda_butonuActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("SÜLEYMAN DEMİREL ÜNİVERSİTESİ\nBİLGİSAYAR MÜHENDİSLİĞİ BÖLÜMÜ\nYAZILIM MÜHENDİSLİĞİ DERSİ\nDÖNEM ÖDEVİ İÇİN HAZIRLANMIŞ\nBİR PROJEDİR. HİÇ BİR TİCARİ\nAMACI BULUNMAMAKTADIR.\nEĞER SORUN TEŞKİL EDEN DURUM\nSÖZ KONUSU OLDUYSA VEYA\nPROGRAMIN GELİŞTİRİLMESİ İÇİN\nÖNERİNİZ VARSA LÜTFEN SOSYAL\nMEDYA ADRESLERİMİZE VEYA \nASKURUCU ÜYEMİZ OLAN \nHASAN ALİ YILDIR'IN\n EMAİL ADRESİ \nOLAN tinim123@gmail.com ADRESİNE \nYAZINIZ. GÖRÜŞ VE ÖNERİLERİNİZ\nBİZİM İÇİN ÖNEMLİDİR.\n\nKURUCU ÜYELER : \nAYŞE İPEK YILMAZ\nHASAN ALİ YILDIR\nÖZLEM YILMAZ\nKENAN YILMAZ\nNEVİN İN ");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(hakkimizda_butonu)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(instagram_butonu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(facebook_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(twitter_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(cikis_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(kalan, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kalan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(instagram_butonu)
                            .addComponent(facebook_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twitter_butonu)
                            .addComponent(cikis_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(hakkimizda_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cikis_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikis_butonuActionPerformed
       JOptionPane.showMessageDialog(this, "Çıkış Yapılıyor. BIGGANG SİGORTA A.Ş Olarak İyi Günler Dileriz.");
       System.exit(0);
    }//GEN-LAST:event_cikis_butonuActionPerformed

    private void hakkimizda_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hakkimizda_butonuActionPerformed
      new Hakkimizda().show();
      //hakkimizda.setVisible(true);
    }//GEN-LAST:event_hakkimizda_butonuActionPerformed

    private void instagram_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instagram_butonuActionPerformed
      String internet="https://www.instagram.com/biggangsigorta/";
      Desktop d=Desktop.getDesktop();
        try {
            d.browse(new URI(internet));
        } catch (IOException ex) {
            Logger.getLogger(HesapAlani.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(HesapAlani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_instagram_butonuActionPerformed

    private void facebook_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facebook_butonuActionPerformed
      String internet="https://www.facebook.com/B%C4%B0G-GANG-Sigorta-448369702565849/?modal=admin_todo_tour";
      Desktop d=Desktop.getDesktop();
        try {
            d.browse(new URI(internet));
        } catch (IOException ex) {
            Logger.getLogger(HesapAlani.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(HesapAlani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_facebook_butonuActionPerformed

    private void hesap_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesap_butonuActionPerformed

//ARAÇ SİGORTASI İLE İLGİLİ HESAPLAMALAR
 if(arac_paneli.isShowing()==true){//SEÇİLİMİ?
    if(this.yas_secim.getSelectedItem().toString().equals("1-5")){
    this.yasCarpani=100;
    }
    if(this.yas_secim.getSelectedItem().toString().equals("6-10")){
    this.yasCarpani=200;
    }    
    if(this.yas_secim.getSelectedItem().toString().equals("10+")){
    this.yasCarpani=300;
    }  
    if(ton_secim.getSelectedItem().toString().equals("1-2")){
    this.kgCarpani=100;
    }
    if(ton_secim.getSelectedItem().toString().equals("3-5")){
    this.kgCarpani=200;
    }
    if(ton_secim.getSelectedItem().toString().equals("6+")){
    this.kgCarpani=300;
    }

    if(this.model_secim.getSelectedItem().toString().equals("SEDAN")){
    this.modelCarpani=100;
    }  
    if(this.model_secim.getSelectedItem().toString().equals("HATCBACK")){
    this.modelCarpani=50;
    }      
    if(this.model_secim.getSelectedItem().toString().equals("TİCARİ")){
    this.modelCarpani=300;
    }  
    
    if(this.kaza_secim.getSelectedItem().toString().equals("VAR")){
    this.kazaCarpani=500;
    }      
     if(this.kaza_secim.getSelectedItem().toString().equals("YOK")){
    this.kazaCarpani=10;
    }  
    
     this.sonuc_ekrani.setText(Integer.toString(this.aracCarpani+this.yasCarpani+this.modelCarpani+this.kazaCarpani+kgCarpani+100)+" TL ");//EKRANA YAZDIRMA
  
 }
     
     
     
     //SAĞLIK SİGORTASI İLE İLGİLİ HESAPLAMALAR
     if(saglik_paneli.isShowing()==true){//SEÇİLİMİ?
     if(insan_yas.getSelectedItem().toString().equals("17-")){
    JOptionPane.showMessageDialog(this, "18 Yaş Altı Kişiler Bireysel Sağlık Sigortasından Faydalanamazlar");
    }
     else{
    if(insan_yas.getSelectedItem().toString().equals("18-24")){
    this.hyCarpani=200;
    }
    if(insan_yas.getSelectedItem().toString().equals("25-64")){
     this.hyCarpani=350;
    }
    if(insan_yas.getSelectedItem().toString().equals("+65")){
    this.hyCarpani=500;
    }
    if(has_secim.getSelectedItem().toString().equals("HASTALIK YOK")){
    this.hastalikCarpani=300;
    }
    if(has_secim.getSelectedItem().toString().equals("KALP")){
    this.hastalikCarpani=500;
    }
    if(has_secim.getSelectedItem().toString().equals("BEYİN")){
    this.hastalikCarpani=600;
    }
       this.sonuc_ekrani.setText(Integer.toString(200+this.hyCarpani+this.hastalikCarpani)+" TL ");//EKRANA YAZDIRMA
     }
 }
     
     
     //DEPREM SİGORTASI İLE İLGİLİ İŞLEMLERİ YAPTIĞIMIZ ALAN
    if(deprem_paneli.isShowing()==true){//SEÇİLİMİ?
    if(bina_yas_secim.getSelectedItem().toString().equals("1-5")){
    this.binaYas=200;
    }
    if(bina_yas_secim.getSelectedItem().toString().equals("6-9")){
    this.binaYas=320;
    }
    if(bina_yas_secim.getSelectedItem().toString().equals("10+")){
    this.binaYas=410;
    }
    if(bina_kat.getSelectedItem().toString().equals("BODRUM")){
    this.katNo=185;
    }
    if(bina_kat.getSelectedItem().toString().equals("1-2")){
    this.katNo=255;
    }
    if(bina_kat.getSelectedItem().toString().equals("3-5")){
    this.katNo=300;
    }
    if(bina_kat.getSelectedItem().toString().equals("6-9")){
    this.katNo=350;
    }
    if(bina_kat.getSelectedItem().toString().equals("10+")){
    this.katNo=500;
    }
    if(bina_kat.getSelectedItem().toString().equals("MÜSTAKİL")){
    this.katNo=220;
    }
    if(bina_hasar.getSelectedItem().toString().equals("VAR")){
    this.depremKazaCarpani=1000;
    }
    if(bina_hasar.getSelectedItem().toString().equals("YOK")){
    this.depremKazaCarpani=0;
    }
    sonuc_ekrani.setText(Integer.toString(300+this.depremKazaCarpani+this.katNo+this.binaYas)+" TL ");//YAZDIRMA
    }
   
     
    }//GEN-LAST:event_hesap_butonuActionPerformed

    private void twitter_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twitter_butonuActionPerformed
        String internet="https://twitter.com/BiggangSigorta";
        Desktop d=Desktop.getDesktop();
        try {
            d.browse(new URI(internet));
        } catch (IOException ex) {
            Logger.getLogger(HesapAlani.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(HesapAlani.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_twitter_butonuActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad_alani;
    private javax.swing.JPanel arac_paneli;
    private javax.swing.JComboBox bina_hasar;
    private javax.swing.JComboBox bina_kat;
    private javax.swing.JComboBox bina_yas_secim;
    private javax.swing.JButton cikis_butonu;
    private javax.swing.JPanel deprem_paneli;
    private javax.swing.JLabel email_alani;
    private javax.swing.JButton facebook_butonu;
    private javax.swing.JButton hakkimizda_butonu;
    private javax.swing.JComboBox has_secim;
    private javax.swing.JButton hesap_butonu;
    private javax.swing.JComboBox insan_yas;
    private javax.swing.JButton instagram_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel kalan;
    private javax.swing.JComboBox kaza_secim;
    private javax.swing.JLabel kullanici_adi_alani;
    private javax.swing.JComboBox model_secim;
    private javax.swing.JPanel saglik_paneli;
    private javax.swing.JTextArea sonuc_ekrani;
    private javax.swing.JLabel soyad_alani;
    private javax.swing.JTabbedPane tabbed_pane;
    private javax.swing.JComboBox ton_secim;
    private javax.swing.JButton twitter_butonu;
    private javax.swing.JComboBox yas_secim;
    // End of variables declaration//GEN-END:variables
}
